apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-wiki
  namespace: services
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::400472617168:role/prod-be-wiki-role

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: be-wiki
spec:
  externalSecretName: be-wiki
  refreshTime: 15s
  namespaceSelector:
    matchLabels:
      app.kubernetes.io/name: services
  externalSecretSpec:
    refreshInterval: 15s
    secretStoreRef:
      name: driffle-parameter-store
      kind: ClusterSecretStore
    target:
      name: be-wiki
      creationPolicy: Owner
      deletionPolicy: Delete
    data:
      - secretKey: APP_SECRET
        remoteRef:
          key: /conf/prod/forkmost/APP_SECRET
      - secretKey: DATABASE_URL
        remoteRef:
          key: /conf/prod/forkmost/DATABASE_URL
      - secretKey: AWS_S3_REGION
        remoteRef:
          key: /conf/prod/forkmost/AWS_S3_REGION
      - secretKey: AWS_S3_BUCKET
        remoteRef:
          key: /conf/prod/forkmost/AWS_S3_BUCKET
      - secretKey: AWS_S3_BUCKETS
        remoteRef:
          key: /conf/prod/forkmost/AWS_S3_BUCKET
